"""add ingredient categories table

Revision ID: 9d208bbef725
Revises: 7dc4d79e188c
Create Date: 2024-10-11 12:53:44.472907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9d208bbef725'
down_revision: Union[str, None] = '7dc4d79e188c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weigth', sa.Float(), nullable=False),
    sa.Column('diabetic', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.Integer(), nullable=False),
    sa.Column('profile_picture', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_ingredients_categories_id'), 'ingredients_categories', ['id'], unique=False)
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.add_column('user_roles', sa.Column('permissions', sa.String(length=255), nullable=False))
    op.drop_index('role', table_name='user_roles')
    op.drop_column('user_roles', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('role', 'user_roles', ['role'], unique=True)
    op.drop_column('user_roles', 'permissions')
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weigth', mysql.FLOAT(), nullable=False),
    sa.Column('diabetic', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('account_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_picture', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_ingredients_categories_id'), table_name='ingredients_categories')
    op.drop_table('ingredients_categories')
    # ### end Alembic commands ###
